apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  ports:
  - name: 80-9192
    port: 80
    protocol: TCP
    targetPort: 9192
  selector:
    app: order-service
  type: ClusterIP
status:
  loadBalancer: {}
