apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-service
    spec:
      containers:
      - image: mbashirli/order-service:latest
        name: order-service
        resources: {}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: "true"
status: {}
