apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-order
  name: mysql-order
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-order
  type: ClusterIP
status:
  loadBalancer: {}
