apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql-order
  name: mysql-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-order
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-order
    spec:
      containers:
      - image: mysql:8.3
        name: mysql
        resources: {}
        env:
          - name: MYSQL_DATABASE
            value: order
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_ROOT_PASSWORD
            value: password
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-order-pvc
status: {}
