apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
spec:
  ports:
  - name: 9092-9092
    port: 29092
    protocol: TCP
    targetPort: 29092
  selector:
    app: broker
  type: ClusterIP
status:
  loadBalancer: {}
