apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notification-service
  name: notification-service
spec:
  ports:
  - name: 80-9091
    port: 80
    protocol: TCP
    targetPort: 9091
  selector:
    app: notification-service
  type: ClusterIP
status:
  loadBalancer: {}
