apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notification-service
    spec:
      containers:
      - image: mbashirli/notification-service
        name: notification-service
        resources: {}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "broker:29092"
status: {}
