apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: 22181
      targetPort: 2181
      name: client
  selector:
    app: zookeeper
status:
  loadBalancer: {}