apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-server
  name: redis-server
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-server
  type: ClusterIP
status:
  loadBalancer: {}
